import { Chip, Paper, Stack, Typography } from "@mui/material";
import { alpha } from "@mui/material/styles";
import type { CodeReviewAgentReview } from "@taxes/shared";

import { buildAgentReviewPresentation } from "../agent-review-presentation.js";

interface AgentReviewPanelProps {
  readonly review: CodeReviewAgentReview;
}

export function AgentReviewPanel({ review }: AgentReviewPanelProps) {
  const presentation = buildAgentReviewPresentation(review);

  return (
    <Paper
      sx={(theme) => ({
        backgroundColor: alpha(theme.palette.secondary.main, 0.06),
        p: 2.5
      })}
      variant="outlined"
    >
      <Stack spacing={1.5}>
        <Stack spacing={0.5}>
          <Typography variant="subtitle2">Advisory Agent Review</Typography>
          <Typography color="text.secondary" variant="body2">
            {presentation.summary}
          </Typography>
          <Typography color="text.secondary" variant="body2">
            Generated by {review.reviewer}. Human review remains the final gate.
          </Typography>
        </Stack>
        <Paper
          sx={(theme) => ({
            backgroundColor: alpha(theme.palette.background.default, 0.72),
            p: 1.5
          })}
          variant="outlined"
        >
          <Stack spacing={0.75}>
            <Typography variant="subtitle2">What to do with this advisory pass</Typography>
            <Typography variant="body2">{presentation.nextAction}</Typography>
          </Stack>
        </Paper>
        {presentation.groups.map((group) => (
          <FindingGroup
            actionLabel={group.actionLabel}
            items={group.items}
            key={group.title}
            title={group.title}
          />
        ))}
      </Stack>
    </Paper>
  );
}

function FindingGroup({
  actionLabel,
  items,
  title
}: {
  readonly actionLabel: string;
  readonly items: ReturnType<typeof buildAgentReviewPresentation>["groups"][number]["items"];
  readonly title: string;
}) {
  return (
    <Paper
      sx={(theme) => ({
        backgroundColor: alpha(theme.palette.background.paper, 0.94),
        p: 1.5
      })}
      variant="outlined"
    >
      <Stack spacing={1.25}>
        <Stack direction="row" flexWrap="wrap" gap={1}>
          <Typography variant="subtitle2">{title}</Typography>
          <Chip label={actionLabel} size="small" variant="outlined" />
        </Stack>
        {items.map((item) => (
          <Stack key={`${title}-${item.title}`} spacing={0.75}>
            <Stack direction="row" flexWrap="wrap" gap={1}>
              <Chip label={item.title} size="small" variant="outlined" />
              <Chip label={`${item.lensLabel} | ${item.confidenceLabel}`} size="small" variant="outlined" />
            </Stack>
            <Typography variant="body2">{item.summary}</Typography>
          </Stack>
        ))}
      </Stack>
    </Paper>
  );
}
