import { Chip, Paper, Stack, Typography } from "@mui/material";
import { alpha } from "@mui/material/styles";
import type { CodeReviewAgentFinding, CodeReviewAgentReview } from "@taxes/shared";

interface AgentReviewPanelProps {
  readonly review: CodeReviewAgentReview;
}

export function AgentReviewPanel({ review }: AgentReviewPanelProps) {
  return (
    <Paper
      sx={(theme) => ({
        backgroundColor: alpha(theme.palette.secondary.main, 0.06),
        p: 2.5
      })}
      variant="outlined"
    >
      <Stack spacing={1.5}>
        <Stack spacing={0.5}>
          <Typography variant="subtitle2">Advisory Agent Review</Typography>
          <Typography color="text.secondary" variant="body2">
            {review.summary}
          </Typography>
          <Typography color="text.secondary" variant="body2">
            Generated by {review.reviewer}. Human review remains the final gate.
          </Typography>
        </Stack>
        {review.findings.map((finding) => (
          <FindingCard finding={finding} key={finding.id} />
        ))}
      </Stack>
    </Paper>
  );
}

function FindingCard({ finding }: { readonly finding: CodeReviewAgentFinding }) {
  return (
    <Paper
      sx={(theme) => ({
        backgroundColor: alpha(theme.palette.background.paper, 0.94),
        p: 1.5
      })}
      variant="outlined"
    >
      <Stack spacing={1}>
        <Stack direction="row" flexWrap="wrap" gap={1}>
          <Chip label={finding.title} size="small" variant="outlined" />
          <Chip color={toActionColor(finding.suggestedAction)} label={toActionLabel(finding.suggestedAction)} size="small" />
          <Chip label={`${finding.lens} | ${finding.confidence} confidence`} size="small" variant="outlined" />
        </Stack>
        <Typography variant="body2">{finding.summary}</Typography>
        <Typography color="text.secondary" variant="body2">
          {finding.rationale}
        </Typography>
        {finding.evidence.map((item) => (
          <Typography key={`${finding.id}-${item}`} variant="body2">
            {item}
          </Typography>
        ))}
      </Stack>
    </Paper>
  );
}

function toActionColor(action: CodeReviewAgentFinding["suggestedAction"]): "error" | "info" | "success" | "warning" {
  switch (action) {
    case "accept-now":
      return "success";
    case "follow-up":
      return "warning";
    case "reject":
      return "error";
  }
}

function toActionLabel(action: CodeReviewAgentFinding["suggestedAction"]): string {
  switch (action) {
    case "accept-now":
      return "Accept for this PR";
    case "follow-up":
      return "Approve as follow-up";
    case "reject":
      return "Reject for now";
  }
}
