param(
  [Parameter(Mandatory = $true)][string]$TaskId,
  [string]$BranchName = "",
  [string]$BaseBranch = "main",
  [string]$ApiBase = "http://localhost:3001",
  [string]$Owner = "codex",
  [string[]]$Goals = @(),
  [string[]]$Steps = @(),
  [string[]]$Risks = @()
)

$ErrorActionPreference = "Stop"

$task = (Invoke-RestMethod -Method Get -Uri "$ApiBase/tasks/$TaskId").record
if (-not $task) {
  throw "Task not found via API: $TaskId"
}

if (-not $BranchName -or $BranchName.Trim().Length -eq 0) {
  $canonicalTaskId = ""
  if ($task.metadata -and $task.metadata.canonicalTaskId) {
    $canonicalTaskId = "$($task.metadata.canonicalTaskId)"
  }

  $resolvedBranchName = node ./scripts/resolve-task-branch-name.mjs --task-id $TaskId --canonical-task-id $canonicalTaskId --title "$($task.title)"
  if ($LASTEXITCODE -ne 0 -or -not $resolvedBranchName) {
    throw "Failed to resolve task branch name for task $TaskId"
  }
  $BranchName = $resolvedBranchName.Trim()
}

./scripts/start-task-branch.ps1 -TaskId $TaskId -BranchName $BranchName -BaseBranch $BaseBranch -ApiBase $ApiBase | Out-Null

$metadata = @{}
if ($task.metadata) {
  foreach ($p in $task.metadata.PSObject.Properties) {
    $metadata[$p.Name] = $p.Value
  }
}

$workflow = @{}
if ($metadata.workflow) {
  foreach ($p in $metadata.workflow.PSObject.Properties) {
    $workflow[$p.Name] = $p.Value
  }
}
$workflow.owner = $Owner
$metadata.workflow = $workflow

$goalList = if ($Goals.Count -gt 0) { $Goals } else { @("Define planning goals for this task") }
$stepList = if ($Steps.Count -gt 0) { $Steps } else { @("Define implementation steps for this task") }
$riskList = if ($Risks.Count -gt 0) { $Risks } else { @("Identify key execution risks for this task") }

$metadata.planningArtifact = @{
  createdAt = (Get-Date).ToString("o")
  goals = $goalList
  steps = $stepList
  risks = $riskList
}
$testingArtifacts = @{}
if ($metadata.testingArtifacts) {
  foreach ($p in $metadata.testingArtifacts.PSObject.Properties) {
    $testingArtifacts[$p.Name] = $p.Value
  }
}

$testingPlanned = @{}
if ($testingArtifacts.planned) {
  foreach ($p in $testingArtifacts.planned.PSObject.Properties) {
    $testingPlanned[$p.Name] = $p.Value
  }
}
$testingImplemented = @{}
if ($testingArtifacts.implemented) {
  foreach ($p in $testingArtifacts.implemented.PSObject.Properties) {
    $testingImplemented[$p.Name] = $p.Value
  }
}

if (-not $testingPlanned.gherkinScenarios) {
  $testingPlanned.gherkinScenarios = @("Given <context>, When <action>, Then <expected outcome>")
}
if (-not $testingPlanned.unitTestIntent) {
  $testingPlanned.unitTestIntent = @("Define unit-test intent for core logic paths")
}
if (-not $testingPlanned.integrationTestIntent) {
  $testingPlanned.integrationTestIntent = @("Define integration-test intent for workflow boundaries")
}
if (-not $testingPlanned.notes) {
  $testingPlanned.notes = "Planning-stage test design scaffold generated by begin-task."
}
if (-not $testingImplemented.testsAddedOrUpdated) {
  $testingImplemented.testsAddedOrUpdated = @()
}
if (-not $testingImplemented.evidenceLinks) {
  $testingImplemented.evidenceLinks = @()
}
if (-not $testingImplemented.commandsRun) {
  $testingImplemented.commandsRun = @()
}
if (-not $testingImplemented.notes) {
  $testingImplemented.notes = $null
}

$metadata.testingArtifacts = @{
  schemaVersion = "1.0"
  planned = $testingPlanned
  implemented = $testingImplemented
}
$metadata.transitionNote = "Begin-task script created branch and planning artifact; awaiting plan approval."

$patch = @{
  status = "planning"
  metadata = $metadata
} | ConvertTo-Json -Depth 25

$updated = Invoke-RestMethod -Method Patch -Uri "$ApiBase/tasks/$TaskId" -ContentType "application/json" -Body $patch
if (-not $updated.record -or $updated.record.status -ne "planning") {
  throw "Failed to keep task in planning after begin-task update: $TaskId"
}

[PSCustomObject]@{
  taskId = $updated.record.id
  status = $updated.record.status
  branchName = $BranchName
  owner = $Owner
  nextStep = "Review and approve planningArtifact before transition to implementing."
} | ConvertTo-Json -Depth 8
